/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/1093_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/1093_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/1129_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/1129_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/1401_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/1401_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/14562_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/14562_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
wait
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/17089_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/17089_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/1874_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/1874_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/6519_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/6519_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/CDC-1311_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/CDC-1311_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
wait
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/CDC-R13976_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/CDC-R13976_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/CDC-x33_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/CDC-x33_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/MD14_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/MD14_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/MbovisKNP440440_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/MbovisKNP440440_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
wait
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R11138_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R11138_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R1171_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R1171_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R1210_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R1210_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R12931_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R12931_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
wait
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R13587_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R13587_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R13614_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R13614_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R13976_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R13976_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R14645_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R14645_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
wait
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R14816_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R14816_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R16074_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R16074_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R202_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R202_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R2311_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R2311_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
wait
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R2660_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R2660_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R4018_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R4018_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R4440_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R4440_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R5688_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R5688_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
wait
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R721_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R721_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R8498_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R8498_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R884_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R884_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/R912_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/R912_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
wait
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/SA135_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/SA135_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/SA145_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/SA145_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/SA154_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/SA154_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/SA219_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/SA219_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
wait
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/SA248_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/SA248_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/SA61_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/SA61_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/SA622_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/SA622_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/SA62_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/SA62_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
wait
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/SA98_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/SA98_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/SAWC1116_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/SAWC1116_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/SAWC337_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/SAWC337_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/SAWC4203_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/SAWC4203_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
wait
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/SAWC5557_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/SAWC5557_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/TT321_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/TT321_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/TT50_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/TT50_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/X139_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/X139_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
wait
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/X173_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/X173_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/X70_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/X70_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/X72_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/X72_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/marieta-BA23_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/marieta-BA23_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
wait
/home/adippenaar/USAP_H37Rv/Tools/samtools-1.3/samtools mpileup -t AD -ugf /home/adippenaar/USAP_H37Rv/Reference/MycobacteriumTuberculosis_H37Rv/FASTA/H37Rv_4411532_updated_13_jun_2013.fasta /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/Alignment_Files/r394_trim_novo_realigned_resorted_dedup.bam | /home/adippenaar/USAP_H37Rv/Tools/bcftools-1.3/bcftools call -vmO v -o /home/adippenaar/run_seqs_06_02_2018_out/Results/NOVO/VARIANTS/r394_trim_novo_realigned_resorted_dedup_VARIANTS_SAMTOOLS.vcf &
wait
