/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1035-C11_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1035-C11_trim_smalt_sort_RG.sam RGID=R1035-C11 RGSM=R1.fastq RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1035-C11_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1035-C1_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1035-C1_trim_smalt_sort_RG.sam RGID=R1035-C11 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1035-C1_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1035-C8_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1035-C8_trim_smalt_sort_RG.sam RGID=R1035-C1 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1035-C8_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1415-C1_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1415-C1_trim_smalt_sort_RG.sam RGID=R1035-C1 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1415-C1_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1415-C3_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1415-C3_trim_smalt_sort_RG.sam RGID=R1035-C8 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1415-C3_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1415-C4_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1415-C4_trim_smalt_sort_RG.sam RGID=R1035-C8 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R1415-C4_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R160-C13_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R160-C13_trim_smalt_sort_RG.sam RGID=R1415-C1 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R160-C13_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R160-C3_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R160-C3_trim_smalt_sort_RG.sam RGID=R1415-C1 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R160-C3_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R160-C7_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R160-C7_trim_smalt_sort_RG.sam RGID=R1415-C3 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R160-C7_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R376-C11_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R376-C11_trim_smalt_sort_RG.sam RGID=R1415-C3 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R376-C11_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R376-C5_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R376-C5_trim_smalt_sort_RG.sam RGID=R1415-C4 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R376-C5_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R376-C8_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R376-C8_trim_smalt_sort_RG.sam RGID=R1415-C4 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R376-C8_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R458-C3_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R458-C3_trim_smalt_sort_RG.sam RGID=R160-C13 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R458-C3_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R458-C4_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R458-C4_trim_smalt_sort_RG.sam RGID=R160-C13 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R458-C4_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R458-C6_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R458-C6_trim_smalt_sort_RG.sam RGID=R160-C3 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R458-C6_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R486-C10_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R486-C10_trim_smalt_sort_RG.sam RGID=R160-C3 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R486-C10_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R486-C1_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R486-C1_trim_smalt_sort_RG.sam RGID=R160-C7 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R486-C1_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R631-C2_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R631-C2_trim_smalt_sort_RG.sam RGID=R160-C7 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R631-C2_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R631-C3_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R631-C3_trim_smalt_sort_RG.sam RGID=R376-C11 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R631-C3_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R631-C9_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R631-C9_trim_smalt_sort_RG.sam RGID=R376-C11 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R631-C9_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R637-C10_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R637-C10_trim_smalt_sort_RG.sam RGID=R376-C5 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R637-C10_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R637-C5_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R637-C5_trim_smalt_sort_RG.sam RGID=R376-C5 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R637-C5_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R637-C8_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R637-C8_trim_smalt_sort_RG.sam RGID=R376-C8 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R637-C8_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R641-C1_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R641-C1_trim_smalt_sort_RG.sam RGID=R376-C8 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R641-C1_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R641-C4_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R641-C4_trim_smalt_sort_RG.sam RGID=R458-C3 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R641-C4_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R641-C6_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R641-C6_trim_smalt_sort_RG.sam RGID=R458-C3 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R641-C6_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R721-C13_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R721-C13_trim_smalt_sort_RG.sam RGID=R458-C4 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R721-C13_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R721-C14_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R721-C14_trim_smalt_sort_RG.sam RGID=R458-C4 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R721-C14_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R721-C1_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R721-C1_trim_smalt_sort_RG.sam RGID=R458-C6 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R721-C1_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R810-C14_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R810-C14_trim_smalt_sort_RG.sam RGID=R458-C6 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R810-C14_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R810-C15_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R810-C15_trim_smalt_sort_RG.sam RGID=R486-C10 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R810-C15_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R810-C3_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R810-C3_trim_smalt_sort_RG.sam RGID=R486-C10 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R810-C3_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R810-C9_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R810-C9_trim_smalt_sort_RG.sam RGID=R486-C1 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R810-C9_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R912-C11_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R912-C11_trim_smalt_sort_RG.sam RGID=R486-C1 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R912-C11_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R912-C12_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R912-C12_trim_smalt_sort_RG.sam RGID=R631-C2 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R912-C12_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R912-C1_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R912-C1_trim_smalt_sort_RG.sam RGID=R631-C2 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R912-C1_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R965-C1_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R965-C1_trim_smalt_sort_RG.sam RGID=R631-C3 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R965-C1_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R965-C8_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R965-C8_trim_smalt_sort_RG.sam RGID=R631-C3 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R965-C8_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R966-C11_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R966-C11_trim_smalt_sort_RG.sam RGID=R631-C9 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R966-C11_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R966-C13_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R966-C13_trim_smalt_sort_RG.sam RGID=R631-C9 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R966-C13_trim_smalt_sort.sam
/home/ndc/USAP/Tools/jre1.7.0_51/bin/java -jar /home/ndc/USAP/Tools/picard-tools-1.107/AddOrReplaceReadGroups.jar INPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R966-C5_trim_smalt_sort.sam OUTPUT=/home/ndc/single_col_out/Results/SMALT/Alignment_Files/R966-C5_trim_smalt_sort_RG.sam RGID=R637-C10 RGSM=12345 RGPL=Illumina RGPU=run RGLB=unknown
rm /home/ndc/single_col_out/Results/SMALT/Alignment_Files/R966-C5_trim_smalt_sort.sam
